sudo: false

matrix:
  fast_finish: true
  include:
    - os: linux
      language: c++
      env: CMAKE_COMPILER=clang++-3.8
      addons:
        apt:
          packages:
            - clang-3.8
    - os: linux
      language: c++
      env: CMAKE_COMPILER=g++-6
      addons:
        apt:
          packages:
            - g++-5
    - os: osx
      language: objective-c
      env: CMAKE_COMPILER=clang++

install:

script: CXX=${CMAKE_COMPILER} ./build_and_test.sh
